export const EXTENSION_NAME = process.env.PLASMO_PUBLIC_EXTENSION_NAME
export const PUBLIC_KEY = process.env.PLASMO_PUBLIC_PUBLIC_KEY
export const PRIVATE_KEY = process.env.PLASMO_PUBLIC_PRIVATE_KEY
export const IS_ENCRYPT_SETUP = PUBLIC_KEY && PRIVATE_KEY
